#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
ACCOUNT="secrets-rsync"
SECRETS_DIR=/usr/local/lib/$ACCOUNT
unset FORCED_GID # FORCED_GID="-g 500" # to specify the group id integer
unset FORCED_UID # FORCED_UID="-u 500" # to specify the user id integer
useradd -d $SECRETS_DIR -c "secrets distribution" -m -r $FORCED_GID $FORCED_UID $ACCOUNT
mkdir -p ${SECRETS_DIR}/.ssh
chmod 700 ${SECRETS_DIR}/.ssh
if sestatus | grep -q 'policy name:[ 	]*targeted'; then
    # assumes recent CentOS policy
    chcon -u unconfined_u -r object_r -t ssh_home_t ${SECRETS_DIR}/.ssh
fi
chmod -R u+rwX,g-rwx,o-rwx $SECRETS_DIR
chown -Rh ${ACCOUNT}:${ACCOUNT} $SECRETS_DIR
